name: Docker Image CI Master 

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - 
      name: Build the Docker image - Notifiation API
      run: docker build -f WebApi/Dockerfile . --tag youcall/api-vpp:${{ secrets.MAJOR }}.${{ secrets.MINOR }} --tag youcall/api-vpp:latest   
    - 
      name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub - VPP API Versioned Tag
      run: docker push youcall/api-vpp:${{ secrets.MAJOR }}.${{ secrets.MINOR }}   
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: ${{ secrets.PROJECT_NAME }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}  
